### PR TITLE
Swap to upstream ftd2xx

### PR DESCRIPTION
**Pull request by daniel-veecle**
This PR attempts to reduce the complexity of `tricore-docker` by swapping the hardcoded implementation of FTDI with upstream https://crates.io/crates/libftd2xx.

By doing so, one can refactor code to be simpler and easier to understand.

This PR does **not** aim to improve the RPC protocol, logic or probe functionalities - this is left for future work. 

## Status

The code is kind of finished... but it needs to be tested so for now this is kept as draft.

### CODE REVIEW

**Comment by daniel-veecle** [comment]
I compiled this on our Linux workstation and stub tested and it seemed to work. I need to test with actual hardware but for that I will wait Monday. In the meantime this is ready for review (In the assumption it works).

**Comment by daniel-veecle** [comment]
I guess this can be closed @arctic-alpaca?

**Comment by arctic-alpaca** [comment]
Depends on whether we can land https://github.com/veecle/tricore-probe/pull/23. But if so, then yes.

**Comment by arctic-alpaca** [comment]
Superseded by #23.

**Pull request closed without merging**
